//************************************************************************************
//**  
//**  File name:     C:\projects\magicwand\xc8\magicwand.c
//**  Generated by:  Flowcode v4.2.3.58
//**  Date:          Monday, May 04, 2015 07:43:07
//**  Licence:       Professional
//**  Registered to: 20ACM8
//**  
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F72
#define MX_SPI
#define MX_SPI_C
#define MX_SPI_SDI 4
#define MX_SPI_SDO 5
#define MX_SPI_SCK 3
#define MX_I2C
#define MX_MI2C
#define MX_I2C_C
#define MX_I2C_SDA 4
#define MX_I2C_SCL 3
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 2

//Functions
#define MX_CLK_SPEED 19660800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3faa
#endif
#ifdef HI_TECH_C
__CONFIG(0x3faa);
#endif

//Internal functions
#include "C:\Program Files (x86)\Matrix Multimedia\Flowcode V4\FCD\internals.h"

//Macro function declarations


//Variable declarations



//Macro implementations

void main()
{
	
	//Initialisation
	adcon1 = 0x07;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//Loop
	//Loop: While 1
	while (1)
	{
		//Output
		//Output: 1 -> PORT C
		trisc = 0x00;
		portc = 1;


		//Delay
		//Delay: 1 s
		delay_s(1);


		//Output
		//Output: 0 -> PORT C
		trisc = 0x00;
		portc = 0;


		//Delay
		//Delay: 1 s
		delay_s(1);


	}


	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



